version: '3.4'

services:
  discountdb:
   image: mongo
  basketdb:
   image: redis
  orderdb:
   image: mcr.microsoft.com/mssql/server:2019-latest
  rabbitmq:
   image: rabbitmq:3-management-alpine
  portainer:
    image: portainer/portainer-ce
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.Api/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile


  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Discount.Grpc/Dockerfile


  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Ordering.Api/Dockerfile
  OcelotApiGw:
    image: ${DOCKER_REGISTRY-}OcelotApiGw
    build:
      context: .
      dockerfile: OcelotApiGw/Dockerfile
volumes:
  mongo_data:
  portainer_data: